--[[
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
why are you skidding?
‮]]Players = game:GetService("Players")

--[[‮]]Targets = {
    --[[‮]]"k5utils"
}

--[[‮]]TargetPlrs = {}
--[[‮]]for _,v in Targets do
    --[[‮]]table.insert(TargetPlrs, Players:FindFirstChild(v))
--[[‮]]end

--[[‮]]function notif(title, desc, dur)
    --[[‮]]game:GetService("StarterGui"):SetCore("SendNotification",{
        --[[‮]]Title = title,
        --[[‮]]Text = desc,
        --[[‮]]Duration = dur,
    --[[‮]]})
--[[‮]]end

--[[‮]]_G.s = not _G.s

--[[‮]]notif("Unrenderer",tostring(_G.s),1.2)

--[[‮]]while _G.s do
    --[[‮]]for _,Target in TargetPlrs do
        --[[‮]]TChar = Target.Character
        --[[‮]]for _,v in TChar:GetChildren() do
            --[[‮]]if v:IsA("Accessory") then
                --[[‮]]v:Destroy()
            --[[‮]]end
        --[[‮]]end
    --[[‮]]end
    --[[‮]]task.wait()
--[[‮]]end
